%Plot each of the co-efficients generated by ExpGaussFitLoop101214 against%
%dose from a specific matrix (x) and print each figure to a tif in Dropbox%
%Phd/2014/MatlabExpGaussFits/temp

%%%%%%%%%%%%%%%%%Plot co-efficient a with standard errors%%%%%%%%%%%%%%%%%%
%%%% Plot 1 %%%%
%Plot the change co-efficient 'a' which relates to the gradient of the
%exponential against dose with standard errors shown. X-axis is dose 
%(kilograys),Y-axis has no units.

x=EstimatedDosekGy(1:maxspec,1);

ya=(CoeffSpectra(1,1,1:maxspec));   %Co-efficient a

scatter(x,ya,'filled','k');
hold on;

%%%%
%Error bars
yae1=(CoeffSpectra(5,1,1:maxspec));   % Coeff a minus standard error
yae2=(CoeffSpectra(6,1,1:maxspec));   % Coeff a plus standard error
%scatter(x,yae1,'k','^');

hold on

%scatter(x,yae2,'v','k');
hold on
%Natural log of 'a' standard errors
logyae1=(CoeffSpectra(8,1,1:maxspec));
logyae2=(CoeffSpectra(9,1,1:maxspec));

scatter(x,logyae1,'^','k');
hold on
scatter(x,logyae2,'v','k');

%%Plot 1 formatting 
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Black: Exponential co-efficient')
title('Change in exponential gaussian co-efficient (parameter a) of UV in response to X-ray absorption (kGy)')


print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure1')


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(2)   %%%%Plot co-efficient b with standard errors%%%%%
yb=(CoeffSpectra(1,2,1:maxspec));
ybe1=(CoeffSpectra(5,2,1:maxspec));   % Coeff b minus standard error
ybe2=(CoeffSpectra(6,2,1:maxspec));   % Coeff b plus standard error

scatter(x,yb,'filled','r');  %Scatter coeff b vs dose filled blue
hold on
%scatter(x,ybe1,'b','^');
hold on
%scatter(x,ybe2,'v','b');
hold on
%Natural log of 'b' standard errors
logybe1=(CoeffSpectra(8,2,1:maxspec));
logybe2=(CoeffSpectra(9,2,1:maxspec));
scatter(x,logybe1,'^','r');
hold on
scatter(x,logybe2,'v','r');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Red: Exponential x-offset (b) co-efficient')
title('Plot of changes in x-offset of exponential fit (parameter b) to UV-Vis absorbance in response to X-ray absorption (kGy)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure2')


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(3)   %%%%Plot co-efficient c with standard errors%%%%%
yc=(CoeffSpectra(1,3,1:maxspec));
yce1=(CoeffSpectra(5,3,1:maxspec));   % Coeff c minus standard error
yce2=(CoeffSpectra(6,3,1:maxspec));   % Coeff c plus standard error

scatter(x,yc,'filled','b');  %Scatter coeff c vs dose filled blue
hold on
scatter(x,yce1,'b','^');
hold on
scatter(x,yce2,'v','b');
hold on
%Natural log of 'c' standard errors
logyce1=(CoeffSpectra(8,3,1:maxspec));
logyce2=(CoeffSpectra(9,3,1:maxspec));
%scatter(x,logyce1,'^','k');
hold on
%scatter(x,logyce2,'v','k');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Blue: Exponential half life co-efficient(c)')
title('Exponential half life (parameter c) plotted against X-ray dose absorbed (kilograys)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure3')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(4)   %%%%Plot co-efficient d with standard errors%%%%%
yd=(CoeffSpectra(1,4,1:maxspec));
yde1=(CoeffSpectra(5,4,1:maxspec));   % Coeff d minus standard error
yde2=(CoeffSpectra(6,4,1:maxspec));   % Coeff d plus standard error

scatter(x,yd,'filled','k');  %Scatter coeff d vs dose filled black
hold on
scatter(x,yde1,'k','^');
hold on
scatter(x,yde2,'v','k');
hold on
%Natural log of 'd' standard errors
logyde1=(CoeffSpectra(8,4,1:maxspec));
logyde2=(CoeffSpectra(9,4,1:maxspec));
%scatter(x,logyde1,'^','k');
hold on
%scatter(x,logyde2,'v','k');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Black: Area under 280 gaussian co-efficient(d)')
title('Area under 280 nm gaussian (parameter d) plotted against X-ray dose absorbed (kilograys)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure4')


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(5)   %%%%Plot co-efficient e with standard errors%%%%%
ye=(CoeffSpectra(1,5,1:maxspec));
yee1=(CoeffSpectra(5,5,1:maxspec));   % Coeff e minus standard error
yee2=(CoeffSpectra(6,5,1:maxspec));   % Coeff e plus standard error

scatter(x,ye,'filled','r');  %Scatter coeff e vs dose filled red
hold on
scatter(x,yee1,'r','^');
hold on
scatter(x,yee2,'v','r');
%Natural log of 'e' standard errors
logyee1=(CoeffSpectra(8,5,1:maxspec));
logyee2=(CoeffSpectra(9,5,1:maxspec));
%scatter(x,logyee1,'^','r');

%scatter(x,logyee2,'v','r');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Black: Sigma of the 280 gaussian co-efficient(e)')
title('280 nm gaussian sigma (parameter e) plotted against X-ray dose absorbed (kilograys)')


print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure5')


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(6)   %%%%Plot co-efficient f with standard errors%%%%%
yf=(CoeffSpectra(1,6,1:maxspec));
yfe1=(CoeffSpectra(5,6,1:maxspec));   % Coeff f minus standard error
yfe2=(CoeffSpectra(6,6,1:maxspec));   % Coeff f plus standard error

scatter(x,yf,'filled','g');  %Scatter coeff e vs dose filled blue
hold on
scatter(x,yfe1,'g','^');
hold on
scatter(x,yfe2,'v','g');
%Natural log of 'f' standard errors
logyfe1=(CoeffSpectra(8,6,1:maxspec));
logyfe2=(CoeffSpectra(9,6,1:maxspec));
%scatter(x,logyfe1,'^','k');

%scatter(x,logyfe2,'v','k');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Wavelength (nm)') % y-axis label
legend('Green: Wavelength of first gaussian max absorbance co-efficient(f)')
title('Wavelength of first gaussian peak(parameter f) plotted against X-ray dose absorbed (kilograys)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure6')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(7)   %%%%Plot co-efficient h with standard errors%%%%%
yh=(CoeffSpectra(1,7,1:maxspec));
yhe1=(CoeffSpectra(5,7,1:maxspec));   % Coeff h minus standard error
yhe2=(CoeffSpectra(6,7,1:maxspec));   % Coeff h plus standard error

scatter(x,yh,'filled','k');  %Scatter coeff h vs dose filled black
hold on
scatter(x,yhe1,'k','^');
hold on
scatter(x,yhe2,'v','k');
%Natural log of 'h' standard errors
logyhe1=(CoeffSpectra(8,7,1:maxspec));
logyhe2=(CoeffSpectra(9,7,1:maxspec));
%scatter(x,logyhe1,'^','k');

%scatter(x,logyhe2,'v','k');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Black: Area under 320 nm gaussian co-efficient(h)')
title('Area under 320 nm gaussian co-efficient(h) plotted against X-ray dose absorbed (kilograys)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure7')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(8)   %%%%Plot co-efficient k with standard errors%%%%%
yk=(CoeffSpectra(1,8,1:maxspec));
yke1=(CoeffSpectra(5,8,1:maxspec));   % Coeff k minus standard error
yke2=(CoeffSpectra(6,8,1:maxspec));   % Coeff k plus standard error

scatter(x,yk,'filled','r');  %Scatter coeff k vs dose filled red
hold on
scatter(x,yke1,'r','^');
hold on
scatter(x,yke2,'v','r');
%Natural log of 'k' standard errors
logyke1=(CoeffSpectra(8,8,1:maxspec));
logyke2=(CoeffSpectra(9,8,1:maxspec));
%scatter(x,logyke1,'^','k');

%scatter(x,logyke2,'v','k');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Red: Sigma of 320 nm gaussian(k)')
title('Sigma of 320 nm gaussian (k) plotted against X-ray dose absorbed (kilograys)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure8')


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(9)   %%%%Plot co-efficient l with standard errors%%%%%
yl=(CoeffSpectra(1,9,1:maxspec));
yle1=(CoeffSpectra(5,9,1:maxspec));   % Coeff l minus standard error
yle2=(CoeffSpectra(6,9,1:maxspec));   % Coeff l plus standard error

scatter(x,yl,'filled','g');  %Scatter coeff l vs dose filled green
hold on
scatter(x,yle1,'g','^');
hold on
scatter(x,yle2,'v','g');
%Natural log of 'l' standard errors
logyle1=(CoeffSpectra(8,9,1:maxspec));
logyle2=(CoeffSpectra(9,9,1:maxspec));
%scatter(x,logyle1,'^','k');

%scatter(x,logyle2,'v','k');
xlabel('Dose (kilogray)') % x-axis label
ylabel('Wavelength (nm)') % y-axis label
legend('Green: Wavelength of second gaussian absorbance max(l)')
title('Wavelength of second gaussian peak (parameter l) plotted against dose (kilograys)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure9')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(10)

yn=(CoeffSpectra(1,10,1:maxspec));  %Coefficient n
scatter(x,yn,'filled','g');
hold on
yne1=(CoeffSpectra(5,10,1:maxspec));   % Coeff n minus standard error
yne2=(CoeffSpectra(6,10,1:maxspec));   % Coeff n plus standard error
hold on

scatter(x,yne1,'g','^');

hold on

scatter(x,yne2,'v','g');

%Natural log of 'l' standard errors
logyne1=(CoeffSpectra(8,10,1:maxspec));
logyne2=(CoeffSpectra(9,10,1:maxspec));
%scatter(x,logyle1,'^','k');

%scatter(x,logyle2,'v','k');




%%Plot 10 formatting
xlabel('Dose (kilogray)') % x-axis label
ylabel('Co-efficient value') % y-axis label
legend('Green: Y-offset (n) co-efficient')
title('Plot of changes in y-offset of gaussian fit (parameter n (nm)) against X-ray dose absorbed (kilograys)')

print('-dtiffn','-r100','/Users/matt/Dropbox/Pdx1project/PhD/2014/MatlabExpGaussFits/temp/figure10')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%Clear variables
clearvars y* logy log*e2 log*e1 














