function [fitresult, gof] = createFit(WL, Abs)
%CREATEFIT(WL,ABS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : WL
%      Y Output: Abs
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Oct-2015 12:02:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( WL, Abs );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -4 -Inf];
opts.StartPoint = [703228.656828793 -4 -0.063985526283281];
opts.Upper = [Inf -4 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'Abs vs. WL', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel WL
%ylabel Abs
%grid on


